### ISSUE TITLE
i keep getting this error when i try to run the webconverter.py script

### ISSUE THREAD

**Issue by juden09** [willmendil/ESPBug#44]
Traceback (most recent call last):
  File "C:\Users\D4RK5ID3\ESPBug-0.1\web_converter\webConverter.py", line 8, in <module>
    from css_html_js_minify.minify import process_single_html_file, process_single_js_file, process_single_css_file
  File "C:\Users\D4RK5ID3\ESPBug-0.1\web_converter\css_html_js_minify\__init__.py", line 13, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "C:\Users\D4RK5ID3\ESPBug-0.1\web_converter\css_html_js_minify\minify.py", line 30, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "C:\Users\D4RK5ID3\ESPBug-0.1\web_converter\tutorial_env\lib\site-packages\anglerfish\__init__.py", line 32, in <module>
    from anglerfish.get_clipboard import get_clipboard  # noqa
  File "C:\Users\D4RK5ID3\ESPBug-0.1\web_converter\tutorial_env\lib\site-packages\anglerfish\get_clipboard.py", line 18, in <module>
    Clipboard = NamedTuple("Clipboard", fields=(("copy", callable),
  File "C:\Users\D4RK5ID3\AppData\Local\Programs\Python\Python39-32\lib\typing.py", line 1882, in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
  File "C:\Users\D4RK5ID3\AppData\Local\Programs\Python\Python39-32\lib\typing.py", line 1807, in _make_nmtuple
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "C:\Users\D4RK5ID3\AppData\Local\Programs\Python\Python39-32\lib\typing.py", line 1807, in <dictcomp>
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "C:\Users\D4RK5ID3\AppData\Local\Programs\Python\Python39-32\lib\typing.py", line 164, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: field fields annotation must be a type Got (('copy', <built-in function callable>), ('paste', <built-in function callable>)).

**Comment by Olum0G** [comment]
Same here
