### ISSUE TITLE
Keep getting this error while attempting to run the webconverter.py script. Tried it on both Windows and Linux.

### ISSUE THREAD

**Issue by Olum0G** [willmendil/ESPBug#45]
Traceback (most recent call last):
  File "/home/kali/ESPBug/web_converter/webConverter.py", line 8, in <module>
    from css_html_js_minify.minify import process_single_html_file, process_single_js_file, process_single_css_file
  File "/home/kali/ESPBug/web_converter/css_html_js_minify/__init__.py", line 13, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "/home/kali/ESPBug/web_converter/css_html_js_minify/minify.py", line 30, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "/usr/local/lib/python3.10/dist-packages/anglerfish/__init__.py", line 32, in <module>
    from anglerfish.get_clipboard import get_clipboard  # noqa
  File "/usr/local/lib/python3.10/dist-packages/anglerfish/get_clipboard.py", line 18, in <module>
    Clipboard = NamedTuple("Clipboard", fields=(("copy", callable),
  File "/usr/lib/python3.10/typing.py", line 2324, in NamedTuple
    return _make_nmtuple(typename, fields, module=module)
  File "/usr/lib/python3.10/typing.py", line 2249, in _make_nmtuple
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "/usr/lib/python3.10/typing.py", line 2249, in <dictcomp>
    types = {n: _type_check(t, f"field {n} annotation must be a type")
  File "/usr/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: field fields annotation must be a type Got (('copy', <built-in function callable>), ('paste', <built-in function callable>)).

**Comment by viplameo** [comment]
After a few tests, I found a way to fix this error:
step 1: install python 3.7 + "anglerfish"
step 2: no step 2
